### ISSUE TITLE
issue connecting services together in DC/OS

### ISSUE THREAD

**Issue by frederikanrys** [unterstein/dcos-for-java-devs#2]
Hey Johannes, 

I saw your great talk this week and I was trying to repeat this on my local machine with DC/OS installed in vagrant boxes. (The minimal vagrant setup as described in the get started Manual)

Everything is working fine and seems working nicely, but only my chuck Norris service cannot connect to the database in DC/OS. With docker-compose it all works with no problem. 

1. DC/OS was installed in Vagrant as described on GitHub in the quick start.
https://github.com/dcos/dcos-vagrant/

2. I used the following mesos config for DC/OS (actually, I tried them all with no luck)
https://github.com/unterstein/dcos-for-java-devs/blob/master/marathon-configuration-minimum.json

But each time as I try to access the service via http, I can see the following error in my chuck norris service log file:

> org.springframework.web.util.NestedServletException:
>  Request processing failed; nested exception is org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
> 

Do you have any clue why my to containers cannot connect? Is there a setting I am missing? (I can also see in mesos that both containers are deployed on the same node.)

I would appreciate some help as I am in the dark :(

Regards,
Frederik.

**Comment by unterstein** [comment]
Hey Frederik,

thank you for reporting this to github as well. As discussed via email, do `marathon-configuration-dcos-vagrant.json` solve your issues?

Thanks
Johannes

**Comment by frederikanrys** [comment]
Yes. Thnx.

**Comment by unterstein** [comment]
Great ❤️
